gestion_projet:
    resource: "@GestionProjetBundle/Resources/config/routing.yml"
    prefix:   /


utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation


Bug:
    resource: "@GestionProjetBundle/Resources/config/routing/bug.yml"
    prefix:   /bug   
  
Application:
    resource: "@GestionProjetBundle/Resources/config/routing/application.yml"
    prefix:   /application
    
       
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"          
    
module:
        resource: "@GestionProjetBundle/Resources/config/routing/module.yml"
        prefix:   /module  
        
client:
        resource: "@GestionProjetBundle/Resources/config/routing/client.yml"
        prefix:   /client       
        
projet:
        resource: "@GestionProjetBundle/Resources/config/routing/projet.yml"
        prefix:   /admin/projet   
        
intervenant:
        resource: "@GestionProjetBundle/Resources/config/routing/intervenant.yml"
        prefix:   /intervenant        
        
demande:
        resource: "@GestionProjetBundle/Resources/config/routing/demande.yml"
        prefix:   /demande        