# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app_user.regisration_Listenner:
        class : MedBac\UtilisateursBundle\EventListenner\RegistrationListenner
        
        arguments: []
        
        tags: 
            - { name : kernel.event_subscriber }
            
            
         