projet_index:
    path:     /
    defaults: { _controller: "GestionProjetBundle:Projet:index" }
    methods:  GET

projet_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProjetBundle:Projet:show" }
    methods:  GET

projet_new:
    path:     /new
    defaults: { _controller: "GestionProjetBundle:Projet:new" }
    methods:  [GET, POST]

projet_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProjetBundle:Projet:edit" }
    methods:  [GET, POST]

projet_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProjetBundle:Projet:delete" }
    methods:  DELETE

projet_modifier:
    path:     /modifier
    defaults: { _controller: "GestionProjetBundle:Projet:modifier" } 