<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * intervenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class intervenantRepository extends \Doctrine\ORM\EntityRepository
{
}
