gestion_projet_homepage:
    path:     /
    defaults: { _controller: GestionProjetBundle:Produit:produit }

gestion_projet_application:
    resource: "@GestionProjetBundle/Resources/config/routing/application.yml"
    prefix:   /application

presentation_page:
    path:     /produits
    defaults: { _controller: GestionProjetBundle:Produit:presentation } 
        
Acceuil:
    path:     /acceuil
    defaults: { _controller: GestionProjetBundle:Default:acceuil }   
    
    
myapplication_contact:
    path:     /contact
    defaults: { _controller: GestionProjetBundle:Default:contact }  
    
      