gestion_projet_homepage:
    path:     /
    defaults: { _controller: GestionProjetBundle:Produit:produit }


gestion_projet_application:
    resource: "@GestionProjetBundle/Resources/config/routing/application.yml"
    prefix:   /application



presentation_page:
    path:     /produits
    defaults: { _controller: GestionProjetBundle:Produit:presentation } 
    
panier:
    path:     /panier
    defaults: { _controller: GestionProjetBundle:Panier:panier }   
    
livraison-panier:
    path:     /panier/livraison
    defaults: { _controller: GestionProjetBundle:Panier:livraison }
    
validation-panier:
    path:     /panier/validation
    defaults: { _controller: GestionProjetBundle:Panier:validation } 
    
   
admin:
    path:     /admin
    defaults: { _controller: GestionProjetBundle:Default:AdminPage }   
    
client:
    path:     /client
    defaults: { _controller: GestionProjetBundle:Default:ClientPage } 
    
Info_page:
    path:     /info
    defaults: { _controller: GestionProjetBundle:Default:ShowInfo }   
    
    
User_page:
    path:     /user
    defaults: { _controller: GestionProjetBundle:Default:showUser }      
    
Determineuser_page:
    path:     /isuser
    defaults: { _controller: GestionProjetBundle:Default:Determineuser }   
    
Acceuil:
    path:     /acceuil
    defaults: { _controller: GestionProjetBundle:Default:acceuil }   
    
    
myapplication_contact:
    path:     /contact
    defaults: { _controller: GestionProjetBundle:Default:contact }  
    
    
redirect:
    path:     /home
    defaults: { _controller: GestionProjetBundle:Default:redirect }      
    
    
   